apiVersion: v1
kind: Service
metadata:
  name: undefined-service
spec:
  selector:
    app: undefined
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: undefined
spec:
  selector:
    matchLabels:
      app: undefined
  replicas: 4
  template:
    metadata:
      labels:
        app: undefined
    spec:
      containers:
      - name: undefined
        image: undefined-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000